# Generated by Django 6.0.7 on 2026-07-25 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF only — browsers can\'t render .docx/.doc inline, so the site\'s "View resume" button would silently fall back to a download.', null=True, upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
