# Generated by Django 6.0.7 on 2026-07-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
