# Generated by Django 6.0.7 on 2026-07-25 21:07

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_thumbnail_url_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, help_text='PDF only — browsers can\'t render .docx/.doc inline, so the site\'s "View resume" button would silently fall back to a download.', null=True, storage=projects.models.resume_storage, upload_to='resume/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
